learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Landing page
    path('landing_page/', views.landing_page, name='landing_page'),
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # About page
    path('about/', views.about, name='about'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    # Logout URL with redirection to homepage (index).
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

class Meta:
    verbose_name_plural = 'entries'

def __str__(self):
    """Return a string representation of the model."""
    return f"{self.text[:50]}..."    

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def landing_page(request):
    """Render the landing page for the Learning Log application."""
    return render(request, 'learning_logs/landing_page.html')

def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def about(request):
    """Display the About page."""
    return render(request, 'learning_logs/about.html')

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
        
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form the the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)  

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """ Register a new user. """
    if request.method != 'POST':
        # Display blank registration page.
        form = UserCreationForm()

    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/about.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
        <h1 class="display-4">About Learning Log</h1>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="container mt-4">
    <!-- Reference to Eric Matthes' book -->
    <div class="mb-4">
        <p>This project was inspired by the learning methods outlined in <em>Python Crash Course</em> by Eric Matthes. His book provided valuable insights and examples that guided the development of this application.</p>
    </div>

    <!-- Description of the Learning Log project -->
    <div class="mb-4">
        <p>The inspiration for the Learning Log project stems from a personal need for a centralized space to organize my learning journey effectively. As a lifelong learner with a wide array of interests, I often found myself overwhelmed by the vast amount of information and topics I was engaging with. Keeping track of notes, resources, and insights across various subjects became a challenge, especially as I juggled multiple projects and studies simultaneously.</p>

        <p>To address this issue, I decided to create a simple, user-friendly web application using Django that allows me to log my learning topics and entries in one place. This way, I can easily revisit and expand on previous learnings, identify patterns in my studies, and track my progress over time. The project has become an invaluable tool in my learning process, helping me stay organized and focused.</p>
    </div>

    <!-- Portfolio project description -->
    <div class="mb-4">
        <p>In addition to serving my personal learning needs, I wanted to develop the Learning Log project as part of my portfolio for Holberton School. This project demonstrates my skills in building full-stack web applications and showcases my ability to create functional, user-centric solutions using Django. It is my hope that the Learning Log project will resonate with others facing similar challenges in managing their learning journey and serve as a helpful tool for anyone seeking to stay organized in their educational pursuits.</p>
    </div>

    <!-- Buttons for LinkedIn, GitHub, and Twitter profiles -->
    <div class="d-flex flex-wrap mb-4">
        <a href="https://www.linkedin.com/in/benjamin-semevor-1762395a/" class="btn btn-primary mr-2 mb-2" target="_blank">LinkedIn</a>
        <a href="https://github.com/Paree2512" class="btn btn-dark mr-2 mb-2" target="_blank">GitHub</a>
        <a href="https://twitter.com/BenSemsGh" class="btn btn-info mb-2" target="_blank">Twitter</a>
    </div>

    <!-- Button for the GitHub repository -->
    <div>
        <a href="https://github.com/Paree2512/LearningLog" class="btn btn-success" target="_blank">Learning Log GitHub Repository</a>
    </div>
    <p>
        
    </p>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Learning Log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  
  <style>
    /* Styles to make the footer stick to the bottom of the page */
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh; /* Ensures that the body takes up the full height of the viewport */
    }
    main {
      flex: 1; /* Pushes the footer to the bottom by taking up the remaining space */
    }
    .footer {
      background-color: #f8f9fa; /* Light background color */
      text-align: center; /* Center text */
      padding: 10px; /* Padding for spacing */
      font-size: small; /* Smaller font size */
      border-top: 1px solid #dee2e6; /* Border on the top */
    }
  </style>

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
        Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              Topics</a></li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:about' %}">About</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <form class="nav-link" action="{% url 'users:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Create New Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

  <!-- Footer -->
  <footer class="footer">
    <span class="text-muted">&copy; 2024 Learning Log. All rights reserved.</span>
  </footer>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <style>
    /* Style for centering content in the jumbotron */
    .jumbotron {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      height: 70vh;
    }
  </style>
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>
    <p class="lead">Create your own Learning Log to track 
      your learning journey! Jot down the subjects you're 
      diving into, and whenever you discover something new, 
      add a quick entry summarizing your findings. It's an easy 
      way to see your progress and stay inspired!.</p>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/landing_page.html
{% extends "learning_logs/base.html" %}

{% load static %}

{% block content %}
<!-- Intro Section -->
<section id="intro-section" class="jumbotron text-center">
    <div class="container">
        <h1 class="display-4">Learning Log</h1>
        <p class="lead">A simple web application to organize your learning topics and entries</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Create A User Account To Explore Learning Log &raquo;</a>
    </div>
</section>

<!-- Feature Section -->
<section id="feature-section" class="container mt-5">
    <h2 class="text-center mb-4">Key Features</h2>
    
    <div class="row">
        <!-- Feature 1 -->
        <div class="col-md-6 mb-4">
            <div class="card text-center">
              <div class="card-body">
                <h3 class="card-title">Create New Account</h3>
                <p class="card-text">Create a user account and start using learning logs.</p>
            </div>
                <img src="{% static 'register.png' %}" alt="Feature 1" class="card-img-top">
            </div>
        </div>
        
        <!-- Feature 2 -->
        <div class="col-md-6 mb-4">
            <div class="card text-center">
              <div class="card-body">
                <h3 class="card-title">Add Topics</h3>
                <p class="card-text">Add topics on what you've studied.</p>
            </div>
                <img src="{% static 'add_topics.png' %}" alt="Feature 2" class="card-img-top">
            </div>
        </div>
        
        <!-- Feature 3 -->
        <div class="col-md-10 mx-auto">
            <div class="card text-center">
              <div class="card-body">
                <h3 class="card-title">Add Entries</h3>
                <p class="card-text">Add and edit your entries efficiently.</p>
            </div>
                <img src="{% static 'add_entries.png' %}" alt="Feature 3" class="card-img-top">
                
            </div>
        </div>
    </div>
    <p>
        
    </p>
</section>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Add entry</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %} {% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  <ul>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}
  
  {% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div class="container mt-4">
    <h1 class="display-4">Topics</h1>
</div>
{% endblock page_header %}

{% block content %}
<div class="container mt-4">
    <ul class="list-group">
        {% for topic in topics %}
            <li class="list-group-item">
                <h5>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h5>
            </li>
        {% empty %}
            <li class="list-group-item">
                <h5>No topics have been added yet.</h5>
            </li>
        {% endfor %}
    </ul>

    <div class="mt-4">
        <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add a New Topic</a>
    </div>
</div>
{% endblock content %}